### ISSUE TITLE
iOS App doesn't build with this package

### ISSUE THREAD

**Issue by prakhar1989** [shaqian/flutter_tflite#5]
Hi 

I'm trying to use this package, but I cant get the app to build

```
            ^
    12 warnings generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: targeted OS version does not support use of thread local variables in
    __ZN14EigenForTFLite26NonBlockingThreadPoolTemplINS_20StlThreadEnvironmentEE8ScheduleENSt3__18functionIFvvEEE for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone XR.
```

Any idea what I'm doing wrong? Let me know if there's any other info I can share to help you debug.

Here's how my `pubspec.yaml` file looks like - 

```yaml
name: awesomeapp
description: some desc

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: "^0.8.2+1"
  flutter_slidable: "^0.4.9"
  camera: "0.2.4"
  path_provider: ^0.4.1
  video_player: ^0.5.2
  firebase_core: "^0.2.5+1"
  firebase_storage: ^1.0.4
  http: ^0.12.0
  timeago: ^2.0.9
  image_picker: ^0.4.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  tflite:
    path: ../flutter_tflite/

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/mobilenet_v1_1.0_224.tflite
    - images/
```
