### ISSUE TITLE
runModelOnImage cannot find file

### ISSUE THREAD

**Issue by pbnsilva** [shaqian/flutter_tflite#71]
Hello,

I took the `flutter_realtime_detection` example and modified it to run the SSD model on an image file that is part of my assets. On button click, I do:

```dart
 Tflite.runModelOnImage(
      path: "assets/image.jpg",
    ).then((recognitions) {
      recognitions.map((res) {
        print(res);
      });
    });
```

Yet:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.io.FileNotFoundException: assets/image.jpg: open failed: ENOENT (No such file or directory), null)
```

Yes, `image.jpg` is in my assets:
```yaml
flutter:
  assets:
    - assets/image.jpg
    - assets/ssd_mobilenet.txt
    - assets/ssd_mobilenet.tflite
```

I can replace `image.jpg` in `runModelOnImage` with `ssd_mobilenet.tflite` and I get that `ssd_mobilenet.tflite` isn't found even though it works just fine via the `runModelOnFrame` that is used in the example.

Any thoughts?
